### ISSUE TITLE
Yasaklı kişiler listesindeki araştırma görevlileri

### ISSUE THREAD

**Issue by ThoAppelsin** [onurtemiz/grass#7]
Araştırma görevlileri mecburen aynı zamanda öğrenci olmak durumundalar. Öte yandan, derslere asistan oldukları için platforma katılmaları istenmeyebilir.

[blacklist.json](/onurtemiz/grass/blob/master/backend/blacklist.json) ve [blacklistv2.json](/onurtemiz/grass/blob/master/backend/blacklistv2.json) ise şu an için arada bir yerdeler; [boun/rehber](http://boun.edu.tr/tr-TR/Content/Calisanlar/Personel_Rehberi_Kayitlar)'de mail adresi olanlar (176 kişi) yasaklı durumda, rehberde olmayan (? kişi) veya mail adresi olmayanlar (140 kişi) ise serbest.

Şu satıra `... && blacklist[key]['Title'] != "Araştırma Görevlisi" ...` gibi bir ekleme yapıp, v2'yi yeniden oluşturarak araştırma görevlileri serbest bırakılabilir:

https://github.com/onurtemiz/grass/blob/faef1cc8468a5cf60354226d269cee6342090f43/backend/heh.js#L6

Hepsini engellemek içinse 140 kişinin mail adresini bulmak gerek.

**Comment by onurtemiz** [comment]
Merhabalar, belirttiğiniz gibi Title == 'Araştırma Görevlisi' olanları listeden kaldırdım. Bu 140 kişi ile ilgili sizinle iletişime geçtik. Yardımınız için teşekkürler.
